// Code generated by MockGen. DO NOT EDIT.
// Source: ../auth_usecase.go
//
// Generated by this command:
//
//	mockgen -source=../auth_usecase.go -destination=auth_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "BookingGo/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserUseCaseInterface is a mock of UserUseCaseInterface interface.
type MockUserUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockUserUseCaseInterfaceMockRecorder is the mock recorder for MockUserUseCaseInterface.
type MockUserUseCaseInterfaceMockRecorder struct {
	mock *MockUserUseCaseInterface
}

// NewMockUserUseCaseInterface creates a new mock instance.
func NewMockUserUseCaseInterface(ctrl *gomock.Controller) *MockUserUseCaseInterface {
	mock := &MockUserUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCaseInterface) EXPECT() *MockUserUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserUseCaseInterface) CreateUser(req *entity.CreateUserRequest) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", req)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserUseCaseInterfaceMockRecorder) CreateUser(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserUseCaseInterface)(nil).CreateUser), req)
}

// EmailExists mocks base method.
func (m *MockUserUseCaseInterface) EmailExists(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailExists", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailExists indicates an expected call of EmailExists.
func (mr *MockUserUseCaseInterfaceMockRecorder) EmailExists(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailExists", reflect.TypeOf((*MockUserUseCaseInterface)(nil).EmailExists), email)
}

// GetUserByEmail mocks base method.
func (m *MockUserUseCaseInterface) GetUserByEmail(email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserUseCaseInterfaceMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserUseCaseInterface)(nil).GetUserByEmail), email)
}

// GetUserByID mocks base method.
func (m *MockUserUseCaseInterface) GetUserByID(id int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserUseCaseInterfaceMockRecorder) GetUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserUseCaseInterface)(nil).GetUserByID), id)
}

// UpdateUserData mocks base method.
func (m *MockUserUseCaseInterface) UpdateUserData(id int, updates map[string]any) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserData", id, updates)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserData indicates an expected call of UpdateUserData.
func (mr *MockUserUseCaseInterfaceMockRecorder) UpdateUserData(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserData", reflect.TypeOf((*MockUserUseCaseInterface)(nil).UpdateUserData), id, updates)
}

// UpdateUserProfile mocks base method.
func (m *MockUserUseCaseInterface) UpdateUserProfile(id int, req *entity.UpdateUserProfileRequest) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", id, req)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserUseCaseInterfaceMockRecorder) UpdateUserProfile(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserUseCaseInterface)(nil).UpdateUserProfile), id, req)
}

// MockTotpService is a mock of TotpService interface.
type MockTotpService struct {
	ctrl     *gomock.Controller
	recorder *MockTotpServiceMockRecorder
	isgomock struct{}
}

// MockTotpServiceMockRecorder is the mock recorder for MockTotpService.
type MockTotpServiceMockRecorder struct {
	mock *MockTotpService
}

// NewMockTotpService creates a new mock instance.
func NewMockTotpService(ctrl *gomock.Controller) *MockTotpService {
	mock := &MockTotpService{ctrl: ctrl}
	mock.recorder = &MockTotpServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTotpService) EXPECT() *MockTotpServiceMockRecorder {
	return m.recorder
}

// GenerateSecret mocks base method.
func (m *MockTotpService) GenerateSecret(email string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecret", email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateSecret indicates an expected call of GenerateSecret.
func (mr *MockTotpServiceMockRecorder) GenerateSecret(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecret", reflect.TypeOf((*MockTotpService)(nil).GenerateSecret), email)
}

// ValidateCode mocks base method.
func (m *MockTotpService) ValidateCode(secret, code string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCode", secret, code)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateCode indicates an expected call of ValidateCode.
func (mr *MockTotpServiceMockRecorder) ValidateCode(secret, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCode", reflect.TypeOf((*MockTotpService)(nil).ValidateCode), secret, code)
}
