// Code generated by MockGen. DO NOT EDIT.
// Source: ../../auth/blacklist.go
//
// Generated by this command:
//
//	mockgen -source=../../auth/blacklist.go -destination=blacklist_service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBlacklist is a mock of Blacklist interface.
type MockBlacklist struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistMockRecorder
	isgomock struct{}
}

// MockBlacklistMockRecorder is the mock recorder for MockBlacklist.
type MockBlacklistMockRecorder struct {
	mock *MockBlacklist
}

// NewMockBlacklist creates a new mock instance.
func NewMockBlacklist(ctrl *gomock.Controller) *MockBlacklist {
	mock := &MockBlacklist{ctrl: ctrl}
	mock.recorder = &MockBlacklistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklist) EXPECT() *MockBlacklistMockRecorder {
	return m.recorder
}

// AddToBlacklist mocks base method.
func (m *MockBlacklist) AddToBlacklist(ctx context.Context, jti string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToBlacklist", ctx, jti, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToBlacklist indicates an expected call of AddToBlacklist.
func (mr *MockBlacklistMockRecorder) AddToBlacklist(ctx, jti, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToBlacklist", reflect.TypeOf((*MockBlacklist)(nil).AddToBlacklist), ctx, jti, expiresAt)
}

// InvalidateAllSessions mocks base method.
func (m *MockBlacklist) InvalidateAllSessions(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllSessions indicates an expected call of InvalidateAllSessions.
func (mr *MockBlacklistMockRecorder) InvalidateAllSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllSessions", reflect.TypeOf((*MockBlacklist)(nil).InvalidateAllSessions), ctx, userID)
}

// IsInBlacklist mocks base method.
func (m *MockBlacklist) IsInBlacklist(ctx context.Context, jti string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInBlacklist", ctx, jti)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInBlacklist indicates an expected call of IsInBlacklist.
func (mr *MockBlacklistMockRecorder) IsInBlacklist(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInBlacklist", reflect.TypeOf((*MockBlacklist)(nil).IsInBlacklist), ctx, jti)
}

// IsSessionValid mocks base method.
func (m *MockBlacklist) IsSessionValid(ctx context.Context, userID int, issuedAt time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionValid", ctx, userID, issuedAt)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionValid indicates an expected call of IsSessionValid.
func (mr *MockBlacklistMockRecorder) IsSessionValid(ctx, userID, issuedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionValid", reflect.TypeOf((*MockBlacklist)(nil).IsSessionValid), ctx, userID, issuedAt)
}
