// Code generated by MockGen. DO NOT EDIT.
// Source: booking_usecase.go
//
// Generated by this command:
//
//	mockgen -source=booking_usecase.go -destination=mocks/booking_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "BookingGo/internal/entity"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookingRepository) Create(ctx context.Context, booking *entity.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryMockRecorder) Create(ctx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepository)(nil).Create), ctx, booking)
}

// GetAll mocks base method.
func (m *MockBookingRepository) GetAll() ([]entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBookingRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookingRepository)(nil).GetAll))
}

// GetAllBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetAllBookingsByUserID(id int) ([]entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBookingsByUserID", id)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBookingsByUserID indicates an expected call of GetAllBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetAllBookingsByUserID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetAllBookingsByUserID), id)
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(id int) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", id)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), id)
}

// IsSlotAvailable mocks base method.
func (m *MockBookingRepository) IsSlotAvailable(ctx context.Context, start, end time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlotAvailable", ctx, start, end)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlotAvailable indicates an expected call of IsSlotAvailable.
func (mr *MockBookingRepositoryMockRecorder) IsSlotAvailable(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlotAvailable", reflect.TypeOf((*MockBookingRepository)(nil).IsSlotAvailable), ctx, start, end)
}

// SetBookingCancel mocks base method.
func (m *MockBookingRepository) SetBookingCancel(bookingID, userID int) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBookingCancel", bookingID, userID)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBookingCancel indicates an expected call of SetBookingCancel.
func (mr *MockBookingRepositoryMockRecorder) SetBookingCancel(bookingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBookingCancel", reflect.TypeOf((*MockBookingRepository)(nil).SetBookingCancel), bookingID, userID)
}

// SetBookingComplete mocks base method.
func (m *MockBookingRepository) SetBookingComplete(bookingID int) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBookingComplete", bookingID)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBookingComplete indicates an expected call of SetBookingComplete.
func (mr *MockBookingRepositoryMockRecorder) SetBookingComplete(bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBookingComplete", reflect.TypeOf((*MockBookingRepository)(nil).SetBookingComplete), bookingID)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockOutboxRepository) CreateEvent(event *entity.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockOutboxRepositoryMockRecorder) CreateEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockOutboxRepository)(nil).CreateEvent), event)
}

// CreateEventContext mocks base method.
func (m *MockOutboxRepository) CreateEventContext(ctx context.Context, event *entity.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEventContext", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEventContext indicates an expected call of CreateEventContext.
func (mr *MockOutboxRepositoryMockRecorder) CreateEventContext(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEventContext", reflect.TypeOf((*MockOutboxRepository)(nil).CreateEventContext), ctx, event)
}
