// Code generated by MockGen. DO NOT EDIT.
// Source: notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=notification_usecase.go -destination=mocks/notification_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "BookingGo/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CreateNotif mocks base method.
func (m *MockNotificationRepository) CreateNotif(notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotif", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotif indicates an expected call of CreateNotif.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotif(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotif", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotif), notification)
}

// GetAllNotificationsByUserID mocks base method.
func (m *MockNotificationRepository) GetAllNotificationsByUserID(userID int) ([]entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotificationsByUserID", userID)
	ret0, _ := ret[0].([]entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotificationsByUserID indicates an expected call of GetAllNotificationsByUserID.
func (mr *MockNotificationRepositoryMockRecorder) GetAllNotificationsByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotificationsByUserID", reflect.TypeOf((*MockNotificationRepository)(nil).GetAllNotificationsByUserID), userID)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationRepository) MarkAllAsRead(recipientID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", recipientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkAllAsRead(recipientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkAllAsRead), recipientID)
}

// UpdateSettings mocks base method.
func (m *MockNotificationRepository) UpdateSettings(userID int, req *entity.NotificationSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockNotificationRepositoryMockRecorder) UpdateSettings(userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateSettings), userID, req)
}
