package domain

import "errors"

var (
	ErrUserNotFound              = errors.New("user not found")
	ErrBookingNotFound           = errors.New("booking not found")
	ErrEmailTaken                = errors.New("email is taken")
	ErrInvalidEmail              = errors.New("invalid email")
	ErrInvalidPassword           = errors.New("invalid password")
	ErrCurPasswordIsNotCorrect   = errors.New("current password is not correct")
	ErrSamePassword              = errors.New("entered password is the same as current")
	ErrInvalidTimeRange          = errors.New("invalid time range")
	ErrSlotNotAvailable          = errors.New("slot not available")
	ErrInvalidToken              = errors.New("invalid token")
	ErrExpiredToken              = errors.New("token is expired")
	ErrSigningMethodNotSupported = errors.New("signing method not supported")
	ErrNotImplemented            = errors.New("not implemented")
	ErrBookingNotFinished        = errors.New("booking not finished")
	ErrNotificationsAlreadyRead  = errors.New("all notifications is already read")
	ErrBookingIsActive           = errors.New("booking is active right now")
	ErrOnlyForStaffOrAdmin       = errors.New("only for staff or admin")
	ErrTotpAlreadyEnabled        = errors.New("totp already enabled")
	ErrTotpSecretNotSet          = errors.New("totp secret not set")
	ErrInvalidTotpCode           = errors.New("invalid otp secret")
	ErrTotpAlreadyDisabled       = errors.New("totp already disabled")
	ErrNatsConnection            = errors.New("natsClient connection error")
	ErrJetStreamConnection       = errors.New("jetstream connection error")
	ErrStreamAdd                 = errors.New("stream add error")
	ErrStreamAlreadyExists       = errors.New("stream already exists")
	ErrCacheKeyNotFound          = errors.New("cache key not found")
)
